import type { Metadata } from "next";
import "./globals.css";

// next/font import'ları ve kullanımı kaldırıldı.

export const metadata: Metadata = {
  title: "NPC-AI ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*
          next/font yerine standart Google Fonts <link> etiketleri eklendi.
          Bu yöntem, Electron build'i ile uyumludur.
        */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      {/*
        Font sınıf adı (className) body etiketinden kaldırıldı.
        Font artık globals.css üzerinden uygulanacak.
      */}
      <body>{children}</body>
    </html>
  );
}
